/* eslint-disable prettier/prettier */
export enum SortType {
    DESC = 'DESC',
    ASC = 'ASC',
}

export const ERROR_PAGINATION_REQUEST = {
    SORT_TYPE: 'ERROR_PAGINATION_REQUEST_SORT_BY_ASC_OR_DESC',
    FIELD_SORT_NOT_FOUND: 'ERROR_PAGINATION_REQUEST_FIELD_SORT_NOT_FOUND',
    OFFSET_IS_NUMBER: 'ERROR_PAGINATION_REQUEST_OFFSET_MUST_BE_A_NUMBER',
    OFFSET_LESS_THAN_ZERO:
        'ERROR_PAGINATION_REQUEST_OFFSET_MUST_BE_LESS_THAN_ZERO',
    LIMIT_IS_NUMBER: 'ERROR_PAGINATION_REQUEST_LIMIT_MUST_BE_A_NUMBER',
    LIMIT_LESS_THAN_ONE: 'ERROR_PAGINATION_REQUEST_LIMIT_MUST_BE_LESS_THAN_ONE',
};